name: juego_2048
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.4

# 1. DEPENDENCIAS PRINCIPALES 
dependencies:
  flutter:
    sdk: flutter
  # Iconos estilo iPhone
  cupertino_icons: ^1.0.8

# 2. HERRAMIENTAS DE DESARROLLO 
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  # Herramientas para iconos y splash
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.1

# 3. CONFIGURACIONES 

# Configuración del Icono
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21

# Configuración de Pantalla de Carga
flutter_native_splash:
  color: "#FAF8EF"
  image: "assets/icon.png"

# 4. CONFIGURACIÓN DE FLUTTER
flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg